#!/usr/bin/env bash

RED='\033[0;31m'
GREEN='\033[0;32m'
CYAN='\033[1;36m'
NC='\033[0m' # No Color

test_prereqs() {
    command -v python3 >/dev/null || { echo >&2 "Python 3 is required but is not installed"; exit 1; }
}

print_step() {
    echo -e " - ${CYAN}${1}${NC}"
}

indent() { sed 's/^/      /'; }